smtp:
  host: smtp.mail.ru
  port: 465
  user: cadv
  password: <password>
  sender: <user>
rabbitmq:
  url: amqp://guest:guest@localhost:5672/
  exchange: emails
  exchange_type: direct
  queue: user_emails
  consumer_tag: pasteAPI-email-sender
